---
permalink: upgrade/upgrade-ontap-tools.html 
sidebar: sidebar 
keywords: upgrade, ONTAP tools, VMware vSphere, HA, non-HA, low RPO backup, SRA adapter, vCenter Server 
summary: 使用所需的预检查和备份步骤，将 ONTAP tools for VMware vSphere 从 10.4 或 10.5 升级到 10.6，适用于 HA 和非 HA 部署。 
---
= 从 ONTAP tools for VMware vSphere 10.x 升级到 10.6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以直接将 ONTAP tools for VMware vSphere 10.4 或 10.5 升级到 10.6。要从 ONTAP tools 10.0、10.1、10.2 或 10.3 升级到 10.6，请先升级到 10.4 或 10.5。

[NOTE]
====
* 对于 ASA r2 系统，在设置更多存储可用区 (SAZ) 之前，请确保将 ONTAP tools for VMware vSphere 升级到 10.6，并将 ONTAP 升级到 9.16.1。
* 如果从 ONTAP tools for VMware vSphere 10.4 或 10.5 升级到 10.6 失败，则无法回滚。使用低 RPO 或快照恢复来还原设置。对于 ONTAP tools for VMware vSphere 10.3 及更早版本，请使用零 RPO 还原设置。在受保护环境中还原后，重新验证数据存储区保护并验证保护组状态和关系。


====
.开始之前
* 在开始升级之前，请确保所有节点均处于活动状态。
* 确保ONTAP系统证书和已加入的 vCenter 证书有效期至少为 5 天。如果证书提前过期，升级将失败。
* 确保所有节点上都有第五个磁盘，容量为 100 GB。
* 验证节点配置是否符合下表中的规格。


|===
| 部署类型 | 每个节点的 CPU 内核数 | 每个节点的内存 (GB) | 每个节点的磁盘空间 (GB) | 总CPU内核数 | 总内存(GB) | 总磁盘空间 (GB) 


| 小型非HA | 9 | 18 | 350 | 9 | 18 | 350 


| 非HA中型 | 13 | 26 | 350 | 13 | 26 | 350 


| 小型HA | 9 | 18 | 350 | 27 | 54 | 1050 


| HA中等 | 13 | 26 | 350 | 39 | 78 | 1050 


| HA大型 | 17 | 34 | 350 | 51 | 102. | 1050 
|===
* 启用低 RPO 备份，并确保在 vSphere 客户端界面中可见一个备份。请在升级前下载备份文件夹。
* 建议采用低 RPO 备份。但是，在非高可用性部署中，您可以在升级之前对ONTAP工具虚拟机进行静默快照。
+
请参阅 link:../manage/backup-settings.html["编辑备份设置"] 和 link:../manage/recover-backup.html["恢复ONTAP工具设置"] 有关备份和恢复的更多信息。



.步骤
. 将适用于VMware vSphere的ONTAP工具升级ISO上传到内容库。
. 在主 VM 页面中，选择“操作”>“编辑设置”。要确定主虚拟机名称：
+
.. 在任意节点上启用诊断 shell
.. 运行以下命令：
`grep sourceHost /opt/netapp/meta/ansible_vars.yaml`


. 在编辑设置窗口中的*CD/DVD 驱动器*字段下选择*内容库 ISO 文件*。
. 选择 ISO 文件，选中 *CD/DVD 驱动器* 字段的 *已连接* 框，然后单击 *确定*。
. 登录到 vCenter 服务器。
. 找到主 ONTAP tools VM 并启动 Web 控制台。
. 使用 `maint`凭据登录。
. 输入*2*选择*系统配置*菜单。
. 输入 *6* 以选择*升级*选项。
. 出现提示时提供 vCenter 凭据。这是托管 ONTAP tools 的 vCenter 实例。
+
如果您在使用 ONTAP 工具的双 vCenter Server 拓扑结构中——即设备托管在一个 vCenter 实例并管理另一个实例，您可以为托管 ONTAP 工具的 vCenter 实例分配受限角色。您可以创建一个专用的 vCenter 用户和角色，并仅授予其部署 OVF 模板所需的权限。详细信息请参见 link:../concepts/rbac-vcenter-use.html#vsphere-object-hierarchy["适用于VMware vSphere 10的ONTAP工具附带的角色"] 中列出的角色。

+
对于将由ONTAP工具管理的 vCenter 实例，请确保 vCenter 用户帐户具有管理员权限。

+
在升级过程中，如果任何内置存储后端证书缺少主题备用名称 (SAN) 条目，您将收到提示，指出缺少 SAN。如果您选择在未验证 SAN 的情况下继续，升级将继续，但由于存在潜在的安全风险，因此不建议这样做。

. 升级时、系统会自动执行以下操作：
+
.. 网关证书续订有效期为 1 年。当您移除以前的 SRA 适配器并上传新的 10.6 适配器时，SRA 证书的有效期将从 10 年更改为 1 年。
.. 远程插件已升级
.. ONTAP和 vCenter Server 证书经过验证并添加到ONTAP工具中
.. 已启用备份
.. 如果存在 10.5 或更早版本的主机集群保护设置，则 ONTAP tools 会在升级期间创建单独的 *Cluster protection configuration* 导航项。




.下一步行动
升级到 ONTAP tools for VMware vSphere 10.6 后：

* 监控系统警报并计划在一年内网关证书到期之前更新它。
* 卸载 ONTAP tools 10.4 或 10.5 SRA 适配器并上传 10.6 SRA 适配器 tar 文件。
* 上传 SRA 适配器 tar 文件后，运行安装命令。然后，重新扫描 SRA 适配器以更新 VMware Site Recovery Storage Replication Adapters 页面。
* 打开*群集保护配置*并验证现有主机群集保护设置是否存在并正确映射。


升级后您可以：

* 从 ONTAP tools Manager 禁用服务
* 从非HA设置移至HA设置
* 将非 HA 小型配置扩展为非 HA 中型配置，或者扩展为 HA 中型或大型配置。


.相关信息
link:../migrate/migrate-to-latest-ontaptools.html["从 ONTAP tools for VMware vSphere 9.x 迁移到 10.6"]
