---
permalink: upgrade/upgrade-ontap-tools.html 
sidebar: sidebar 
keywords: upgrade 
summary: HA和非HA部署均支持升级。 
---
= 将适用于ONTAP tools for VMware vSphere升级到 10.5
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以从ONTAP tools for VMware vSphere升级到 10.5。但是，要从ONTAP工具 10.0、10.1 或 10.2 升级到 10.5，必须先升级到 10.3 或 10.4，然后再升级到 10.5。

[NOTE]
====
* 对于ASA r2 系统，在设置更多存储可用区 (SAZ) 之前，请确保将ONTAP tools for VMware vSphere升级到 10.5，将ONTAP到 9.16.1。
* 如果从ONTAP tools for VMware vSphere升级到 10.5 失败，则无法回滚。使用低 RPO 或快照恢复来恢复设置。对于ONTAP tools for VMware vSphere，使用零 RPO 来恢复设置。


====
.开始之前
* 确保ONTAP系统证书和已加入的 vCenter 证书有效期至少为 5 天。如果证书提前过期，升级将失败。
* 为确保安全升级，请验证您的证书是否包含主题备用名称 (SAN) 条目。如果证书缺少 SAN 条目，请将证书验证标志设置为 false 以在升级期间绕过 SAN 检查。
* 确保所有节点上都有第五个磁盘，容量为 100 GB。
* 验证节点配置是否符合下表中的规格。


|===
| 部署类型 | 每个节点的CPU (核心)数 | 每个节点的内存(GB) | 每个节点的磁盘空间(GB) | 总CPU (核心) | 内存(GB) | 总磁盘空间(GB) 


| 小型非HA | 9 | 18 | 350 | 9 | 18 | 350 


| 非HA中型 | 13 | 26 | 350 | 13 | 26 | 350 


| 小型HA | 9 | 18 | 350 | 27 | 54 | 1050 


| HA中等 | 13 | 26 | 350 | 39 | 78 | 1050 


| HA大型 | 17 | 34 | 350 | 51 | 102. | 1050 
|===
* 确保已启用 CPU 和 RAM 的热插拔。
* 对于ONTAP tools for VMware vSphere，请在升级之前在ONTAP工具虚拟机上拍摄静默快照。
* 启用低 RPO 备份并确保在 vCenter Client 界面中可见一个备份。
+
请参阅 link:../manage/backup-settings.html["编辑备份设置"] 和 link:../manage/recover-backup.html["恢复ONTAP工具设置"] 有关备份和恢复的更多信息。



.步骤
. 将适用于VMware vSphere的ONTAP工具升级ISO上传到内容库。
. 在主 VM 页面中，选择“操作”>“编辑设置”。要确定主虚拟机名称：
+
.. 在任意节点上启用诊断 shell
.. 运行以下命令：
`grep sourceHost /opt/netapp/meta/ansible_vars.yaml`


. 在编辑设置窗口中的*CD/DVD 驱动器*字段下选择*内容库 ISO 文件*。
. 选择 ISO 文件，选中 *CD/DVD 驱动器* 字段的 *已连接* 框，然后单击 *确定*。
. 从vCenter Server中、打开一个ONTAP工具控制台。
. 以维护用户身份登录。
. 输入*2*选择*系统配置*菜单。
. 输入*7*选择*升级*选项。
+
在升级过程中，如果任何内置存储后端证书缺少主题备用名称 (SAN) 条目，您将收到提示，指出缺少 SAN。如果您选择在未验证 SAN 的情况下继续，升级将继续，但由于存在潜在的安全风险，因此不建议这样做。

. 升级时、系统会自动执行以下操作：
+
.. 网关证书续期，有效期为1年。当您移除之前的 SRA 适配器并上传新的 10.5 适配器时，SRA 证书有效期将从 10 年变为 1 年。
.. 远程插件已升级
.. ONTAP和 vCenter Server 证书经过验证并添加到ONTAP工具中
.. 已启用备份




.下一步行动
升级到适用ONTAP tools for VMware vSphere后：

* 监控系统警报并计划在一年内网关证书到期之前更新它。
* 删除ONTAP工具 10.4 或 10.3 SRA 适配器并上传 10.5 SRA 适配器 tar 文件。然后，重新扫描 SRA 适配器以更新 VMware Site Recovery 存储复制适配器页面。


升级后您可以：

* 从管理器用户界面禁用服务
* 从非HA设置移至HA设置
* 将非 HA 小型配置扩展为非 HA 中型配置，或者扩展为 HA 中型或大型配置。


.相关信息
link:../migrate/migrate-to-latest-ontaptools.html["从ONTAP tools for VMware vSphere迁移到 10.5"]
