---
permalink: deploy/ha-three-node-deployment.html 
sidebar: sidebar 
keywords:  
summary: 您可以在小型、中型或大型配置中配置HA。 
---
= 部署HA配置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在小型、中型或大型配置中配置HA三个节点。HA部署使用三项技术来存储服务数据。

* 小型HA三个节点包含8个CPU、每个节点具有16 GB RAM。
* 中型HA：三个节点包含12个CPU、每个节点具有24 GB RAM。
* 大型HA三个节点包含16个CPU、每个节点具有32 GB RAM。


* 开始之前 *

此任务为您提供了有关如何在小型、中型或高配置中安装HA三个节点的说明。


NOTE: 要部署HA三节点配置、必须创建内容库。link:../deploy/download-ontap-tools.html["创建内容库"]有关此过程、请参见第节。有关详细信息、请参见 https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["创建和使用内容库"]博客。

确保已将OVA导入到内容库中。请随时提供内容库的名称以及您为OVA项目提供的库项目名称。


NOTE: 在继续部署之前、请在安装ONTAP工具期间将清单上的集群分布式资源计划程序(DRS)设置为"保守"。这样可确保虚拟机在安装期间不会迁移。

* 步骤 *

. 登录到vSphere服务器。
. 导航到已创建的资源池、集群或要部署OVA的主机。
. 右键单击所需位置并选择*Deploy OVF temple...*。
+

NOTE: 请勿在VMware vSphere虚拟机所管理的vvol数据存储库上部署适用于该虚拟机的ONTAP工具。

. 通过_.ova_文件的URL选择OVA文件，或者浏览到保存_.ova_文件的文件夹，然后单击*Next*。
. 要从内容库中部署适用于VMware vSphere的ONTAP工具、请执行以下操作：
+
.. 转到您的内容库、然后单击要部署的库项目。
.. 单击*Actions*>*从此模板新建虚拟机*


. 选择计算机资源，然后单击*Next*。
. 查看模板的详细信息，然后单击*Next*。
. 阅读并接受许可协议，然后单击*Next*。
. 选择部署配置，然后单击*Next*。
. 为配置和磁盘文件选择存储，然后单击*Next*。
. 为每个源网络选择目标网络，然后单击*Next*。
. 在*Customize temple*(自定义模板*)窗口中，填写必填字段，然后单击*Next*(下一步*)。
+
** 启用SVM范围后、您应事先使用管理IP地址启用SVM支持。
** 此处提供的信息已在安装过程中进行了正确模式的验证。如果出现差异、Web控制台上会显示一条错误消息、并提示您更正提供的任何错误信息。
** 主机名必须由大写字母(A-z)、小写字母(a-z)、数字(0-9 )或连字符(-)特殊字符组成。如果要配置双堆栈、请指定映射到IPv6地址的主机名。


. 查看*Ready to Complete*(准备完成*)窗口中的详细信息，选择*Complete*(完成*)。
+
创建部署任务后、vSphere任务栏中将显示进度。

. 完成此任务后、打开虚拟机的电源。
+
此时将开始安装。您可以在VM的Web控制台中跟踪安装进度。在安装过程中、系统会验证节点配置。系统会验证在OVF表单的Customize模板下的不同部分下提供的输入。如果出现任何差异、则会显示一个对话框、提示您采取更正操作。

. 在对话框提示符中进行必要的更改。使用Tab键浏览面板并选择*OK*。
+
系统将重新验证提供的值。使用适用于VMware vSphere的ONTAP工具、您可以尝试三次以更正任何无效值。如果在三次尝试后仍无法更正问题、则产品安装将停止、建议您尝试在全新虚拟机上进行安装。



成功安装后、Web控制台将显示适用于VMware vSphere的ONTAP工具的状态。
