---
permalink: deploy/ontap-tools-deployment.html 
sidebar: sidebar 
keywords:  
summary: 适用于VMware vSphere设备的ONTAP工具始终部署为小型单节点、并通过核心服务支持NFS/VMFS数据存储库。 
---
= 部署适用于VMware vSphere的ONTAP工具
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
适用于VMware vSphere设备的ONTAP工具始终部署为小型单节点、并通过核心服务支持NFS/VMFS数据存储库。

* 开始之前 *

VMware中的内容库是一个容器对象、用于存储VM模板、vapp模板和其他类型的文件。使用内容库进行部署可为您提供无缝体验、因为它不依赖于网络连接。


NOTE: 您应将内容库存储在共享数据存储库上、以便集群中的所有主机都可以访问该内容库。在将设备设置更改为HA配置之前、您需要创建一个内容库来存储OVA。内容库模板一旦上传、不应在部署后删除。


NOTE: 要稍后启用HA部署、不应将托管ONTAP工具的虚拟机直接部署在ESXi主机上。而是应将其部署在集群或资源池上。

如果您还没有合适的内容库、请按照以下步骤创建一个：


NOTE: 如果您只打算使用小型单节点部署、则无需创建内容库。

.  `.zip`从下载包含适用于VMware vSphere的ONTAP工具的二进制文件(_.ova_)和签名证书的文件 https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp 支持站点"^]。
. 使用登录到vSphere Client `\https://<vcenterip>/<ui>`
. 选择vSphere Client旁边的水平省略号并选择*内容库*。
. 选择页面右侧的*创建*。
. 提供库的名称并创建内容库。
. 导航到您创建的内容库。
. 选择页面右侧的*Actions*并选择*Import Item*并导入OVA文件。



NOTE: 有关详细信息、请参见 https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["创建和使用内容库"]博客。

确保已将OVA导入到内容库中。


NOTE: 在继续部署之前、请在安装ONTAP工具期间将清单上的集群分布式资源计划程序(DRS)设置为"保守"。这样可确保虚拟机在安装期间不会迁移。

.步骤
.  `.zip`从下载包含适用于VMware vSphere的ONTAP工具的二进制文件(_.ova_)和签名证书的文件 https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp 支持站点"^]。如果已将OVA导入到内容库中、则可以跳过此步骤并继续执行下一步、因为您可以直接从内容库进行部署。
. 登录到vSphere服务器。
. 导航到已创建的资源池、集群或要部署OVA的主机。
. 右键单击所需位置并选择*Deploy OVF temple...*。
+

NOTE: 切勿将适用于VMware vSphere虚拟机的ONTAP工具存储在其管理的vvol数据存储库中。

. 通过_.ova_文件的URL选择OVA文件，或者浏览到保存_.ova_文件的文件夹，然后选择*Next*。
. 要从内容库中部署适用于VMware vSphere的ONTAP工具、请执行以下操作：
+
.. 转到内容库、然后选择要部署的库项目。
.. 选择*Actions*>*New VM from this temple*


. 在*选择虚拟机的名称和文件夹*窗口中，输入虚拟机名称并选择虚拟机的位置。如果选中“*自定义此虚拟机的硬件*”复选框，则在进入“准备完成”窗口之前，会启用一个名为“*自定义硬件*”的步骤。
. 选择计算机资源，然后选择*Next*。您可以选择选中*自动启动已部署的VM*复选框。
. 查看模板的详细信息，然后选择*Next*。
. 阅读并接受许可协议，然后选择*Next*。
. 为配置和磁盘文件选择存储，然后选择*Next*。
. 为每个源网络选择目标网络，然后选择*Next*。
. 在*自定义模板*窗口中，填写必填字段，然后选择*下一步*。
+
** 此处提供的信息已在安装过程中进行了正确模式的验证。如果出现差异、Web控制台上会显示一条错误消息、并提示您更正提供的任何错误信息。
** 主机名必须由大写字母(A-z)、小写字母(a-z)、数字(0-9 )或连字符(-)特殊字符组成。如果要配置双堆栈、请指定映射到IPv6地址的主机名。
+

NOTE: 不支持纯IPv6。具有IPv6和IPv4地址的VLAN支持混合模式。



. 在“*自定义硬件*”窗口中，应启用CPU热添加和内存热插拔。
. 查看*Ready to Complete*(准备完成*)窗口中的详细信息，选择*Complete*(完成*)。
+
创建部署任务后、vSphere任务栏中将显示进度。

. 完成此任务后、打开虚拟机的电源。
+

NOTE: 在启动之前、请确保虚拟机已为CPU和内存启用热插件。



您可以在VM的Web控制台中跟踪安装进度。

如果在OVF表单中输入的值存在任何差异、则会显示一个对话框、提示您采取更正操作。在对话框中进行必要的更改、使用选项卡按钮导航并选择"确定"。您可以尝试三次以更正任何问题。如果尝试三次后问题仍然存在、则安装过程将停止、建议您在新虚拟机上重试安装。
