---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: 您应创建保护组来保护受保护站点上的一组虚拟机。 
---
= 配置受保护站点和恢复站点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您应创建保护组来保护受保护站点上的一组虚拟机。

添加新的数据存储区时，您可以将其添加到现有的数据存储区组中，也可以添加新的数据存储区并创建新的卷或一致性组以进行保护。将新的数据存储区添加到受保护的一致性组或卷后，更新SnapMirror并在受保护站点和恢复站点上执行存储发现。您可以手动或按计划运行发现，以确保检测到并保护新的数据存储区。



== 将受保护站点和恢复站点配对

您应对使用vSphere Client创建的受保护站点和恢复站点进行配对、以使Storage Replication Adapter (SRA)能够发现存储系统。


NOTE: 存储复制适配器 (SRA) 支持具有自动故障转移双工类型的一个同步关系的扇出以及一致性组上的异步关系 SnapMirror。但是、不支持在一致性组上使用两个async SnapMirror的扇出或在卷上使用扇出SnapMirors。

.开始之前
* 您应在受保护站点和恢复站点上安装VMware Live Site Recovery。
* 您应已在受保护站点和恢复站点上安装SRA。


.步骤
. 双击vSphere Client主页上的*站点恢复*并选择*站点*。
. 选择*Objects*>*Actions*>*P对 站点*。
. 在*配对Site Recovery Manager服务器*对话框中，输入受保护站点的平台服务控制器的地址，然后选择*下一步*。
. 在 Select vCenter Server 部分中，执行以下操作：
+
.. 验证受保护站点的 vCenter Server 是否显示为要配对的匹配候选服务器。
.. 输入SSO管理凭据、然后选择*完成*。


. 如果出现提示，请选择*Yes*接受安全证书。


.结果
受保护站点和恢复站点都将显示在对象对话框中。



== 配置保护组

.开始之前
您应确保已为以下项配置源站点和目标站点：

* 已安装相同版本的VMware Live Site Recovery
* 虚拟机
* 已配对的受保护站点和恢复站点
* 源数据存储库和目标数据存储库应挂载到相应的站点上


.步骤
. 登录到 vCenter Server 并选择“Site Recovery”>“Protection Groups”。
. 在*Protection Groups*窗格中，选择*New*。
. 指定保护组的名称和说明、方向并选择*下一步*。
. 在“类型”字段中，选择“数据存储组（基于阵列的复制）”作为 NFS 和 VMFS 数据存储区的“类型”字段选项...*。故障域仅包含已启用复制的 SVM。系统会显示仅实施了对等连接且没有问题的 SVM。
. 在复制组选项卡中，选择已启用的阵列对或已配置虚拟机的复制组，然后选择*Next*。
+
复制组上的所有虚拟机都会添加到此保护组中。

. 您可以选择现有的恢复计划，也可以通过选择“添加到新恢复计划”来创建新的恢复计划。
. 在准备完成选项卡中，查看您创建的保护组的详细信息，然后选择*Complete*。

