---
permalink: protect/configure-storage-replication-adapter-for-san-environment.html 
sidebar: sidebar 
keywords:  
summary: '在运行Storage Replication Adapter \(SRA\) for VMware Live Site Recovery之前、应先设置存储系统。' 
---
= 为SAN和NAS环境配置SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在运行适用于VMware Live Site Recovery的Storage Replication Adapter (SRA)之前、应先设置存储系统。



== 为SAN环境配置SRA

.开始之前
您应在受保护站点和恢复站点上安装以下程序：

* VMware Live Site Recovery：VMware 站点提供了 VMware Live Site Recovery 的安装文档。
+
https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["关于VMware Live Site Recovery"]

* SRA：在 VMware Live Site Recovery 上安装适配器。


.步骤
. 验证主 ESXi 主机是否已连接到受保护站点上主存储系统中的 LUN 。
. 验证LUN是否位于具有的igroub中 `ostype` 选项在主存储系统上设置为_vmware_。
. 验证恢复站点上的 ESXi 主机是否与存储虚拟机 (SVM) 具有适当的 iSCSI 和光纤通道连接。辅助站点 ESXi 主机应该能够访问辅助站点存储，主站点 ESXi 主机应该能够访问主站点存储。
+
为此、您可以验证ESXi主机是否已在SVM或上连接本地LUN `iscsi show initiators` 命令。
在ESXi主机中检查映射的LUN的LUN访问、以验证iSCSI连接。





== 为NAS环境配置SRA

.开始之前
您应在受保护站点和恢复站点上安装以下程序：

* VMware Live Site Recovery：您可以在 VMware 网站上找到 VMware Live Site Recovery 的安装文档 - https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["关于VMware Live Site Recovery"]
* SRA：在 VMware Live Site Recovery 和 SRA 服务器上安装适配器。


.步骤
. 验证受保护站点上的数据存储库是否包含已向 vCenter Server 注册的虚拟机。
. 验证受保护站点上的 ESXi 主机是否已挂载 Storage Virtual Machine （ SVM ）中的 NFS 导出卷。
. 使用阵列管理器向导将阵列添加到 VMware Live Site Recovery 时，请验证“*NFS 地址*”字段中指定的有效地址（例如，存在 NFS 导出的 IP 地址或 FQDN）。请勿在“*NFS 地址*”字段中使用 NFS 主机名。
. 使用 `ping` 命令、以验证此主机是否具有可访问用于从SVM提供NFS导出的IP地址的VMkernel端口。

