---
permalink: protect/update-credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: 要使VMware Live Site Recovery能够与SRA进行通信、您应在修改了SRA凭据的情况下更新VMware Live Site Recovery服务器上的SRA凭据。 
---
= 在 ONTAP tools 中更新 SRA 凭据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要使VMware Live Site Recovery能够与SRA进行通信、您应在修改了SRA凭据的情况下更新VMware Live Site Recovery服务器上的SRA凭据。

.开始之前
您应该已经执行了主题中提到的步骤 link:../protect/configure-on-srm-appliance.html["在VMware Live Site Recovery设备上配置SRA"]。

.步骤
. 运行以下命令以从 VMware Live Site Recovery 计算机中删除缓存的 ONTAP tools 凭据：
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd conf/`
.. `rm -rf *`


. 运行Perl命令为SRA配置新凭据：
+
.. `cd ..`
.. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>` 您需要在密码值周围使用一个引号。
+
将显示确认存储凭据已存储的成功消息。SRA 可以使用提供的 IP 地址、端口和凭据与 SRA 服务器进行通信。







== 更改证书后在 VMware Live Site Recovery 设备中重新配置 vCenter

如果 vCenter 证书发生更改，例如在 vCenter 升级后，您可能会在 Site Recovery 扩展上遇到指纹不匹配错误。请执行以下步骤来解决问题。

.步骤
. 在 VMware Live Site Recovery 设备中重新配置 vCenter
+
.. 在浏览器中打开 VMware Live Site Recovery 设备管理界面： `\https://<SRM_IP>:5480`
.. 选择 *Summary* 选项卡。
.. 为 vCenter Server 连接选择 *重新配置*。
+
这将从 vCenter 获取并接受最新的证书指纹。



. 重新连接站点配对（如果错误仍然存在）
+
如果重新配置后指纹不匹配错误仍然存在：

+
.. 登录到 vCenter 用户界面。
.. 导航到 *Site Recovery* 扩展。
.. 找到 *Site Pairing* 部分。
.. 选择 *Reconnect* 以与更新的证书重新建立站点配对。



