---
permalink: concepts/rbac-ontap-use.html 
sidebar: sidebar 
keywords: ONTAP RBAC deployment, custom roles, user configuration, JSON role definition 
summary: 在生产环境中使用 ONTAP tools 之前，请查看 ONTAP tools 的 ONTAP RBAC 注意事项。 
---
= ONTAP tools for VMware vSphere 中的 ONTAP RBAC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere 通过 ONTAP 支持基于角色的访问控制 (RBAC)，使您能够创建限制访问存储资源的自定义用户和角色。了解配置流程和权限级别有助于您在生产环境中部署 ONTAP tools 之前设置适当的访问控制。



[[overview-of-the-configuration-process]]
== 配置过程概述

ONTAP tools for VMware vSphere支持创建具有自定义角色的ONTAP用户。这些定义打包在一个 JSON 文件中，您可以将其上传到ONTAP集群。您可以根据您的环境和安全需求创建用户并定制角色。

以下部分从高层次描述了主要的配置步骤。有关更多详细信息，请参见 link:../configure/configure-user-role-and-privileges.html["配置ONTAP用户角色和权限"]。

.1.准备
您需要具有ONTAP工具管理器和ONTAP集群的管理凭据。

.2.下载JSON定义文件
登录到ONTAP工具管理器用户界面后、您可以下载包含RBAC定义的JSON文件。

.3.创建具有角色的ONTAP用户
登录到System Manager后、您可以创建用户和角色：

. 选择左侧的*Cluster*，然后选择*Settings*。
. 向下滚动至*用户和角色*并选择 `-->`。
. 在*USERS*下选择*ADD*，然后选择*Virtualization products*。
. 在本地工作站上选择JSON文件并上传。


.4.配置角色
在定义角色时、您需要做出多项管理决策。有关详细信息、请参见<<使用System Manager配置角色>>。



[[configure-the-role-using-system-manager]]
== 使用System Manager配置角色

开始使用System Manager创建新用户和角色并上传JSON文件后、您可以根据环境和需求自定义此角色。



[[core-user-and-role-configuration]]
=== 核心用户和角色配置

RBAC定义会打包为多种产品功能、包括VSC、VASA Provider和SRA的组合。您应选择需要RBAC支持的环境。例如、如果您希望角色支持远程插件功能、请选择VSC。您还需要选择用户名和关联密码。



[[privileges]]
=== 特权

角色权限根据 ONTAP 存储所需的访问级别分为四组。角色所基于的权限包括：

* 发现
+
通过此角色，您可以添加存储系统。

* 创建存储
+
使用此角色可以创建存储。它还包括与发现角色关联的所有Privileges。

* 修改存储
+
使用此角色可以修改存储。它还包括与发现和创建存储角色关联的所有Privileges。

* 销毁存储
+
使用此角色可以销毁存储。它还包括与发现、创建存储和修改存储角色关联的所有Privileges。





[[generate-the-user-with-a-role]]
=== 生成具有角色的用户

为您的环境选择配置选项后，选择 *Add*，ONTAP 将创建用户和角色。所生成角色的名称是以下值的串联：

* JSON文件中定义的常量前缀值(例如、"OTV_10")
* 您选择的产品功能
* 权限集列表。


.示例
`OTV_10_VSC_Discovery_Create`

新用户将显示在*用户和角色*页面的列表中。请注意，HTTP 和 ONTAPI 用户登录方法均受支持。
