---
permalink: automation/create-vvol-workflow.html 
sidebar: sidebar 
keywords: REST APIs, swagger 
summary: 工作流是指完成特定管理任务或目标所需的一个或多个步骤的序列。 
---
= 创建卷数据存储库
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用新卷或现有卷创建卷数据存储库。此外、您还可以结合使用现有卷和新卷来创建FlexVol数据存储库。


NOTE: 检查以确保根聚合未映射到SVM。

在创建数据存储库之前生成JWT令牌、或者在vCenter上将"最大承载令牌寿命"设置为60万、以延长SAML令牌到期时间。

您需要为此API传递x-auth.您可以从Swagger中的身份验证下添加的新API生成此x-auth.

/Virtualization /api/v1/auth/vcenter登录

. 使用新卷创建卷数据存储库。


使用ONTAP REST API获取聚合ID、storage_id (SVM用户ID)。
post /Virtualization /api/v1/vcCenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datases

使用以下URI检查状态：

+

[listing]
----
`\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true`
----
+
NFS数据存储库的请求正文

｛
   "name"："nfsds1"、
   "Protocol"："NFS"、
   "PLATFORM_type"："aff"、
   "moref"："domain-"C8"、
   "volumes"：[
      ｛
         "is_existing"：false、
         "name"："vol_NFS_pvt"、
         "size_in"：2048、
         "space_效率"："thin"、
         "聚合"：｛
            "id"：d7078b3c-3827-4ac9-9273-0a32909455c2"
         ｝、
         "QoS"：｛
            "min_IOS"：200、
            "Max_IOPs"：5000
         ｝
      ｝
   ]、
   "storage_backend"：｛
      "storage_id："654c67bc-0f75-11ee-8a8c-00a09860a3ff"
   ｝
｝

iSCSI数据存储库的请求正文：
｛
   "name"："iSCSI_CUSTOM_"、
   "Protocol"(协议)："iSCSI"、
   "PLATFORM_type"：AFF、
   "moref"："domain-"C1"、
   "volumes"：[
       ｛
           "is_existing"：false、
           "name"："iSCSI_CUSTOM_"、
           "size_in"：8034，
           "space_效率"："thin"、
           "聚合"：｛
               "id"："54fe5dd4-e461-49c8-bb2d-6d62c5d75af2"
           ｝
       ｝
   ]、
   "custom_igroup_name"："igroup1"、
   "storage_backend"：｛
                       "storage_id："eb9d33ab-1960-11ee-9506-00a0985c6d9b"｝
｝
。使用现有卷创建卷数据存储库。

使用ONTAP REST API获取聚合ID和卷ID。

 POST /virtualization/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores
请求正文

....
 {
"name" : "nfsds2",
"protocol" : "nfs",
"platform_type": "aff",
"moref" : "domain-c8",
"volumes" : [
    {
          "is_existing": true,
          "id": "e632a632-1412-11ee-8a8c-00a09860a3ff"
        }
],
"storage_backend": {
                    "storage_id": "33a8b6b3-10cd-11ee-8a8c-00a09860a3ff"    }
....
｝
