---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: 存储后端是ESXi主机用于数据存储的系统。 
---
= 将存储后端添加到ONTAP工具
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用ONTAP tools for VMware vSphere，为您的 ESXi 主机添加和管理存储后端。您可以部署集群或 SVM，启用MetroCluster支持，并验证证书以确保安全连接。您可以使用ONTAP工具管理器或 vSphere 客户端配置存储后端，监控证书状态，并在集群更改后手动重新发现资源。

要在本地添加存储后端，请在ONTAP工具界面中使用集群或 SVM 凭据。本地存储后端仅对选定的 vCenter Server 可用。ONTAP工具将 SVM 映射到 vCenter Server 以进行vVols或 VMFS 数据存储库管理。对于 VMFS 数据存储和 SRA 工作流，您可以使用 SVM 凭据而无需全局映射集群。

要添加全局存储后端，请在ONTAP工具管理器中使用ONTAP集群凭据。全局存储后端支持发现工作流，以识别 vVol 管理所需的集群资源。在多租户环境中，您可以本地添加 SVM 用户来管理vVols数据存储。

如果ONTAP中启用了MetroCluster支持，则将源集群和目标集群都作为本地或全局存储后端加入。

.开始之前
验证证书是否包含有效的主题备用名称 (SAN) 字段。  ONTAP系统使用 SAN 字段来识别集群和 SVM 管理 LIF。

[role="tabbed-block"]
====
.使用ONTAP工具管理器
--

NOTE: 在多租户设置中、您可以全局添加存储后端集群、并在本地添加SVM以使用SVM用户凭据。

.步骤
. 从Web浏览器启动ONTAP工具管理器： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期间提供的适用于VMware vSphere的ONTAP工具管理员凭据登录。
. 从边栏中选择*存储后端*。
. 添加存储后端并提供服务器IP地址或FQDN、用户名和密码详细信息。
+

NOTE: 支持IPv4和IPv6地址管理生命周期。

. 自动获取ONTAP集群证书并授权该证书，或者通过浏览到其位置手动上传。
+

NOTE: 如果需要，您可以从维护控制台禁用主题备用名称 (SAN) 验证。有关说明，请参阅link:../manage/change-valid-flag.html["更改证书验证标志"]。

. 如果您添加的存储后端是MetroCluster配置的一部分， ONTAP工具管理器会显示一条弹出消息以添加对等集群。选择“*添加*”并提供MetroCluster对等存储后端的详细信息。
+

NOTE: ONTAP系统执行切换和切回后，手动运行ONTAP工具发现。



--
.使用vSphere客户端用户界面
--

NOTE: vVols数据存储不支持通过 vSphere Client 用户界面直接添加 SVM 用户。

. 登录到vSphere Client。
. 在快捷方式页面中，选择插件部分下的NetApp ONTAP tools*。
. 从边栏中选择*存储后端*。
. 添加存储后端并提供服务器IP地址、用户名、密码和端口详细信息。
+

NOTE: 您可以使用基于集群的凭据以及 IPv4 或 IPv6 管理 LIF 添加存储后端。要直接添加 SVM 用户，请提供基于 SVM 的凭据以及 SVM 管理 LIF。如果集群已加入，则无法再次从该集群加入 SVM 用户。

. 自动获取ONTAP集群证书并授权该证书，或者通过浏览到其位置手动上传。
. 如果添加的存储后端是MetroCluster配置的一部分，ONTAP工具将显示 *添加MetroCluster对等体* 屏幕。选择*添加对等*以添加对等存储后端。
+

NOTE: ONTAP系统执行切换和切回后，手动运行ONTAP工具发现。



.下一步是什么？
ONTAP工具更新列表以显示新的存储后端。

--
====
ONTAP工具在 *存储后端* 页面上列出了新添加的存储后端。如果证书在 30 天或更短时间内过期， ONTAP工具会在证书过期日期列中显示警告。到期后， ONTAP工具会将存储后端标记为未知，因为它无法连接到存储系统。

.相关信息
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_configure_clusters.html["将集群配置到 MetroCluster 配置中"]
