---
permalink: configure/add-vcenter.html 
sidebar: sidebar 
keywords:  
summary: 将vCenter Server实例添加到适用于VMware vSphere的ONTAP工具中、以配置、管理和保护vCenter Server环境中的虚拟数据存储库。 
---
= 将 vCenter Server 实例添加到ONTAP工具
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
将vCenter Server实例添加到适用于VMware vSphere的ONTAP工具中、以配置、管理和保护vCenter Server环境中的虚拟数据存储库。添加多个 vCenter Server 实例时，需要自定义 CA 证书才能在 ONTAP 工具和每个 vCenter Server 之间进行安全通信。

在 ONTAP tools Manager 中注册 vCenter Server 实例时，请确保 vCenter Server 证书包含有效的使用者备用名称 (SAN) 扩展。SAN 扩展必须同时包含 DNS 和 IP 地址条目。例如：

[listing]
----
X509v3 extensions:
    X509v3 Subject Alternative Name:
        DNS: vcenter.example.com, DNS: vcenter, IP Address: 192.168.0.50
----
如果 vCenter Server 证书不包括 SAN 扩展，或者 SAN 扩展不包含正确的 DNS 或 IP 地址值，则 ONTAP tools 操作可能会由于证书验证错误而失败。

.关于此任务
ONTAP工具与 vCenter Server 集成，可直接从 vSphere 客户端执行配置、快照和数据保护等存储任务。

.步骤
. 打开 Web 浏览器并转到以下 URL： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期间提供的适用于VMware vSphere的ONTAP工具管理员凭据登录。
. 选择* vCenter *>*添加*以载入vCenter Server实例。请提供您的vCenter IP地址或主机名、用户名、密码和端口详细信息。
. 在高级选项中，自动获取 vCenter Server 证书（授权）或手动上传。
+

NOTE: 您不需要管理员帐户即可将vCenter实例添加到ONTAP工具。您可以创建自定义角色、而无需具有有限权限的管理员帐户。有关详细信息、请参见 link:../concepts/rbac-vcenter-use.html["将vCenter Server RBAC与适用于VMware vSphere 10的ONTAP工具结合使用"] 。



将vCenter Server实例添加到ONTAP工具会自动触发以下操作：

* ONTAP工具将 vCenter 客户端插件注册为远程插件。
* 此插件和API的自定义Privileges将应用于vCenter Server实例。
* 创建自定义角色以管理用户。
* 此插件会在vSphere用户界面上显示为快捷方式。

