---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords:  
summary: 适用于VMware vSphere的ONTAP工具可检查并设置最适合NetApp存储系统的ESXi主机多路径设置和HBA超时设置。 
---
= 配置ESXi主机设置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
配置 ESXi 服务器多路径和超时设置有助于维护数据可用性和完整性。如果主路径不可用，它可以自动故障转移到备份存储路径。



== 配置ESXi服务器多路径和超时设置

适用于 VMware vSphere 的 ONTAP 工具可检查并设置最适合 NetApp 存储系统的 ESXi 主机多路径设置和 HBA 超时设置。

.关于此任务
此过程可能需要一些时间，具体取决于您的设置和系统负载。您可以在“近期任务”面板中查看进度。

.步骤
. 在VMware vSphere Web Client的主页页面中、选择*主机和群集*。
. 在VMware vSphere Web Client的快捷方式页面上，选择NetApp ONTAP插件部分下的*VMware tools*。
. 转到适用于VMware vSphere的ONTAP工具插件概述(信息板)中的*ESXi主机兼容性*卡。
. 选择*应用建议设置*链接。
. 在“应用推荐的主机设置”窗口中，选择要更新以使用NetApp推荐设置的主机，然后选择“下一步”。
+

NOTE: 您可以展开ESXi主机以查看当前值。

. 在设置页面中、根据需要选择建议值。
. 在摘要窗格中，检查这些值并选择*Complet*。您可以在最近任务面板中跟踪进度。




== 设置ESXi主机值

使用ONTAP tools for VMware vSphere在 ESXi 主机上设置超时和其他值，以实现最佳性能和故障转移。它根据NetApp测试设置这些值。

您可以在 ESXi 主机上设置以下值：



=== HBA/CNA适配器设置

将以下参数设置为默认值：

* Disk.QFullSampleSize
* Disk.QFullThreshold
* Emulex FC HBA 超时
* QLogic FC HBA 超时




=== MPIO设置

MPIO 设置为NetApp存储系统选择最佳路径。  MPIO 设置选择最佳路径并使用它。

对于高性能环境或使用单个 LUN 数据存储进行测试时，调整循环 (VMW_PSP_RR) 路径选择策略 (PSP) 的负载平衡设置以提高性能。将默认 IOPS 值从 1000 设置为 1。


NOTE: MPIO 设置不适用于 NVMe、NVMe/FC 和 NVMe/TCP 协议。



=== NFS 设置

|===


| 参数 | 将此值设置为... 


| Net.TcpipHeapSize | 32. 


| Net.TcpipHeapMax | 1024 MB 


| NFS.MaxVolumes | 256 


| NFS41.MaxVolumes | 256 


| NFS.MaxQueueDepth | 128或更高 


| NFS.HeartbeatMaxFailures | 10 


| NFS.HeartbeatFrequency | 12 


| NFS.HeartbeatTimeout | 5 
|===