---
permalink: configure/discover-storage-systems-and-hosts.html 
sidebar: sidebar 
keywords: discover storage systems and hosts, ONTAP tools first discovery, ESXi host and LUN discovery, NFS export discovery 
summary: 首次启动时，在 ONTAP tools 中发现 ESXi 主机、LUN、NFS 导出和 NetApp 存储系统。 
---
= 在 ONTAP tools 中发现存储系统和主机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当您首次在 vSphere Client 中启动 ONTAP tools for VMware vSphere 时，它会自动发现 ESXi 主机、其关联的 LUN 和 NFS 导出以及拥有这些资源的 NetApp 存储系统。

.开始之前
* 确保所有 ESXi 主机都已开机并连接。
* 确保所有要发现的存储虚拟机 (SVM) 都在运行，并且每个集群节点至少配置了一个用于正在使用的存储协议 (NFS 或 iSCSI) 的数据 LIF。


.关于此任务
您可以了解新的存储系统或更新现有系统，以获取最新的容量和设置详情。您还可以更改ONTAP tools for VMware vSphere。

发现存储系统时、适用于VMware vSphere的ONTAP工具会从vCenter Server实例管理的ESXi主机收集信息。

.步骤
. 在 vSphere 客户端主页中，选择*主机和群集*。
. 右键单击所需的数据中心，然后选择*NetApp ONTAP tools* > *更新主机和存储数据*。
+
在*Confirm *(确认*)对话框中，确认您的选择。

. 选择已发现的状态为的存储控制器 `Authentication Failure`，然后选择*Actions*>*Modify*。
. 在*修改存储系统*对话框中填写所需信息。
. 对具有的所有存储控制器重复步骤4和5 `Authentication Failure` 状态。


发现过程完成后、请执行以下操作：

* 使用适用于VMware vSphere的ONTAP工具为在适配器设置列、MPIO设置列或NFS设置列中显示警报图标的主机配置ESXi主机设置。
* 提供存储系统凭据。

