---
permalink: configure/install-nfs-vaai-plug-in.html 
sidebar: sidebar 
keywords:  
summary: '您可以使用适用于VMware vSphere的NetApp工具安装适用于VMware vStorage APIS for Array Integration \(VAAI\)的ONTAP NFS插件。' 
---
= 使用ONTAP工具安装 NFS VAAI 插件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS vStorage API for Array Integration (NFS VAAI) 插件将 VMware vSphere 连接到 NFS 存储阵列。使用适用ONTAP tools for VMware vSphere安装 VAAI 插件。这允许 NFS 存储阵列代替 ESXi 主机处理某些存储操作。

.开始之前
* 下载 https://mysupport.netapp.com/site/products/all/details/nfsplugin-vmware-vaai/downloads-tab["适用于 VMware VAAI 的 NetApp NFS 插件"]安装包。
* 确保已安装ESXi主机和vSphere 7.0U3最新修补程序或更高版本以及9.14.1 9.14.1或更高版本。
* 挂载NFS数据存储库。


.步骤
. 登录到vSphere Client。
. 选择插件部分下的*快捷方式*>* NetApp ONTAP tools*。
. 选择*Settings*>*NFS VAAI Tools*。
. 如果您已经将 VAAI 插件上传到 vCenter Server，请在 *现有版本* 中选择 *更改*。如果还没有，请选择*上传*。
. 浏览并选择 `.vib`文件，然后选择*Upload*将文件上传到ONTAP工具。
. 选择*在ESXi主机上安装*、选择要安装NFS VAAI插件的ESXi主机、然后选择*安装*。
+
vSphere Web Client 仅显示可以安装该插件的 ESXi 主机。您可以在“近期任务”部分监控安装进度。

. 安装后手动重新启动ESXi主机。
+
重新启动 ESXi 主机后，ONTAP tools for VMware vSphere会自动检测并启用 NFS VAAI 插件。



.下一步是什么？
安装 NFS VAAI 插件并重新启动 ESXi 主机后，配置 VAAI 副本卸载的 NFS 导出策略。确保出口政策规则满足以下要求：

* 相关的ONTAP卷允许 NFSv4 调用。
* 根用户仍为根用户，并且所有连接父卷中都允许使用 NFSv4。
* 在相关的 NFS 服务器上设置 VAAI 支持选项。


更多信息，请参阅 https://kb.netapp.com/on-prem/ontap/DM/VAAI/VAAI-KBs/Configure_the_correct_NFS_export_policies_for_VAAI_copy_offload["为VAAI副本卸载配置正确的NFS导出策略"]知识库文章。

.相关信息
https://docs.netapp.com/us-en/ontap/nfs-admin/support-vmware-vstorage-over-nfs-concept.html["支持基于 NFS 的 VMware vStorage"]

https://docs.netapp.com/us-en/ontap/nfs-admin/enable-disable-nfsv40-task.html["启用或禁用NFSv4.0"]

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-nfsv42-concept.html#nfs-v4-2-security-labels["ONTAP支持NFSv4.2"]
