---
permalink: configure/protect-cluster.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: 适用于VMware vSphere的ONTAP工具可管理主机集群的保护。 
---
= 使用主机集群保护进行保护
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
适用于VMware vSphere的ONTAP工具可管理主机集群的保护。属于选定SVM且挂载在集群中一个或多个主机上的所有数据存储库都会在主机集群下受到保护。

.开始之前
在保护主机群集之前，请确保满足以下要求：

* 主机集群仅包含来自单个 SVM 的数据存储库。
* 主机群集上的数据存储未安装在群集外的主机上。
* 主机集群上挂载的数据存储是采用iSCSI或FC协议的VMFS数据存储。您不能将vVols、NFS 或 VMFS 数据存储与 NVMe/FC 和 NVMe/TCP 协议一起使用。
* 基于主机上挂载的FlexVol/LUN 卷的数据存储不属于任何一致性组。
* 基于主机上挂载的FlexVol/LUN 卷的数据存储库不属于任何SnapMirror关系。
* 主机群集至少包含一个数据存储区。


.步骤
. 登录到vSphere Client。
. 右键单击主机集群并选择 * NetApp ONTAP工具* > *保护集群*。
. 在保护集群窗口中，系统会自动填写数据存储类型和源存储虚拟机（VM）的详细信息。选择数据存储链接以查看受保护的数据存储。
. 选择*添加关系*。
. 在*添加SnapMirror关系*窗口中、选择*目标Storage VM*和*策略*类型。
+
策略类型可以是异步或自动故障转移双工。

+
如果要将SnapMirror关系添加为AutomatedFailOver双 工类型策略、则必须将目标Storage VM作为存储后端添加到部署适用于VMware vSphere的ONTAP工具的同一vCenter中。

+
在 AutomatedFailOverDuplex 策略类型中，有统一和非统一主机配置。当您选择*统一主机配置*切换按钮时，主机启动器组配置将被隐式复制到目标站点上。有关详细信息，请参阅link:../concepts/ontap-tools-concepts-terms.html["关键概念和术语"] 。

. 如果您选择的主机配置不一致、请为集群中的每个主机选择主机访问(源/目标)。
. 选择 * 添加 * 。
. 您可以使用*修改主机集群保护*操作来编辑主机集群保护。您可以使用省略号菜单选项编辑或删除关系。
. 选择“*保护*”按钮。
+
系统创建一个带有作业 ID 详细信息的 vCenter 任务，并在最近任务面板中显示其进度。这是一个异步任务；用户界面仅显示请求提交状态，并不等待任务完成。

. 要查看受保护的主机集群，请转到 * NetApp ONTAP工具* > *保护* > *主机集群关系*。选择一个一致性组以查看其容量、关联数据存储和子一致性组。


[NOTE]
====
如果需要在创建后一小时内删除保护，请先运行存储发现。

====
.相关信息
https://www.vmware.com/docs/vmware-vsphere-metro-storage-cluster-vmsc["VMware vSphere Metro 存储集群 (vMSC)"^]
