---
permalink: release-notes/whats-new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 10.5, ONTAP tools for VMware vSphere' 
summary: 了解适用于ONTAP tools for VMware vSphere中提供的新功能。 
---
= 适用于ONTAP tools for VMware vSphere的新功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解适用于ONTAP tools for VMware vSphere中提供的新功能。

* *平台资质*


ONTAP tools for VMware vSphere增加了对ASA r2 系统的支持，从而提供了与最新硬件和软件配置的兼容性。此版本还包括与ONTAP 9.16.1 和 9.17.1 的集成，扩展了支持的环境。

* *VMware 资格和认证*


ONTAP tools for VMware vSphere符合当前的 VMware 互操作性认证标准，支持 ESXi 主机和 vCenter Server。

* * MetroCluster支持*


此版本引入了对MetroCluster配置的支持，增强了高可用性和灾难恢复功能。

* *安全和证书管理*


此版本引入了自签名证书的简化管理，增强了用户体验并提高了对安全标准的遵守。它提供了改进的证书验证工作流程，以保护ONTAP tools for VMware vSphere通信的ONTAP和 ONTAP 工具。

* *复制增强*


此版本支持具有分层一致性组的 VMFS 复制，包括ASA r2 系统中的 SRA 和SnapMirror活动同步。它支持零 RPO 备份，以提高数据保护和恢复。

* *升级和迁移*


从以前版本的ONTAP tools for VMware vSphere到ONTAP tools for VMware vSphere的升级和迁移过程旨在无缝且高效，从而最大限度地减少停机时间并确保平稳过渡。



== 支持的ONTAP平台和 vCenter Server 版本

有关版本兼容性的最新详细信息，请参阅 https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["NetApp 互操作性表工具"^]。
