---
permalink: manage/certificate-manage.html 
sidebar: sidebar 
keywords:  
summary: 一个适用于VMware vSphere的ONTAP工具实例可以管理多个vCenter Server实例。适用于VMware vSphere的ONTAP工具使用适用于VASA Provider的自签名证书进行部署。这样、只能为Vvol数据存储库管理一个vCenter Server实例。 
---
= 管理证书
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
一个适用于VMware vSphere的ONTAP工具实例可以管理多个vCenter Server实例。

确保颁发证书的域名映射到多vCenter部署中的虚拟IP地址、在该部署中、自定义CA证书是必需的。对域名执行_nslookup_ check以检查域是否已解析为预期的IP地址。应使用负载平衡器IP地址的域名和IP地址创建证书。


NOTE: 将自签名升级到自定义CA时、不支持将不同的负载平衡器IP地址映射到不同的域。

[role="tabbed-block"]
====
.ONTAP工具证书
--
ONTAP工具选项卡显示证书类型(自签名/CA签名)和域名等详细信息。默认情况下、在部署期间会生成自签名证书。您可以续订此证书或将此证书升级到CA。

* 步骤 *

. 从Web浏览器启动ONTAP工具管理器： `\https://loadBalanceIP:8443/virtualization/ui/`
. 使用您在部署期间提供的适用于VMware vSphere的ONTAP工具管理员凭据登录。
. 选择*Certificates*> ONTAP tools*>*Renew*选项以续订证书。
+

NOTE: 如果证书已过期或即将到期、您可以续订该证书。在续订证书之前、系统将处于脱机状态、您将从用户界面中注销。

+
当证书类型为CA签名时，*Renew*是唯一可用的选项。对于CA签名的证书、将显示一个对话框、您可以在其中提供服务器证书、专用密钥、根CA和中间证书详细信息。

. 要将自签名证书升级为自定义CA证书，请选择*Certificates*>* ONTAP tools*>*升级到CA*选项。
+
.. 在*将证书升级到自定义CA*弹出窗口中，上传服务器证书、服务器证书专用密钥、根CA证书和中间证书文件。工具提示提供证书的问题描述。
.. 输入生成此证书的域名。
.. 单击 * 升级 * 。
+

NOTE: 系统将处于脱机状态、直到升级完成、您将从用户界面中注销。不允许从CA签名证书切换到自签名证书。





--
.VASA提供程序证书
--
适用于VMware vSphere的ONTAP工具使用适用于VASA Provider的自签名证书进行部署。这样、只能为Vvol数据存储库管理一个vCenter Server实例。如果您要管理多个vCenter Server实例、并且要在多个vCenter Server实例上启用vvol功能、则需要使用ONTAP工具管理器界面将自签名证书更改为自定义CA证书。

* 步骤 *

. 从Web浏览器启动ONTAP工具管理器： `\https://loadBalanceIP:8443/virtualization/ui/`
. 使用您在部署期间提供的适用于VMware vSphere的ONTAP工具管理员凭据登录。
. 选择*Certificates*>*VASA Provider*或*VASA ONTAP tools*>*Renew*选项以续订证书。
. 要将自签名证书升级为自定义CA证书，请选择*Certificates*>*VASA Provider*或*VASA ONTAP tools*>*升级到CA*选项。
+
.. 在*将证书升级到自定义CA*弹出窗口中，上传服务器证书、服务器证书专用密钥、根CA证书和中间证书文件。工具提示提供证书的问题描述。
.. 输入生成此证书的域名。
.. 单击 * 升级 * 。
+

NOTE: 系统将处于脱机状态、直到升级完成、您将从用户界面中注销。不允许从CA签名证书切换到自签名证书。





--
====