---
permalink: manage/delete-ds.html 
sidebar: sidebar 
keywords: delete datastore, ONTAP tools datastore removal, delete NFS VMFS vVol datastore, VMware datastore cleanup 
summary: 删除 NFS、VMFS 或 vVols 数据存储，并在删除前检查使用该数据存储的虚拟机。 
---
= 删除 ONTAP tools 中的数据存储区
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 ONTAP tools 在 vCenter Server 中删除 NFS、VMFS 或 vVols 数据存储。删除行为和清理选项因数据存储类型而异。

.NFS 和 VMFS 数据存储的删除行为
* 无法删除虚拟机使用的数据存储。
* 对于受保护的主机群集，适用额外的保护限制。


.vVols 数据存储库的删除行为
对于vVols数据存储区，执行以下操作：

* vVol 容器已卸载。
* 如果未使用 igroup，则将其启动器从 igroup 中删除。
* vVol 容器已被删除。
* FlexVol 卷保留在存储后端。


对于 vVols 数据存储库，只有在所选数据存储库中不存在 vVols 时，您才能删除该数据存储库。

.开始之前
* 验证虚拟机未使用数据存储区。
* 检查数据存储库是否属于受保护的主机集群。
* 在数据存储删除期间，决定是否删除 ONTAP 集群上的备份卷。


[cols="1,1,2,2"]
|===
| 数据存储库类型 | 是否可以删除它? | 主要阻塞条件 | ONTAP 清理选项 


| NFS | 是 | 此数据存储库已被虚拟机占用。 | 如果适用，您可以选择*在 ONTAP 集群上删除卷*。 


| VMFS | 是 | 此数据存储库已被虚拟机占用，或者存在主机群集保护限制。 | 您可以选择*在 ONTAP 集群上删除卷*。对于 ONTAP 存储上的受保护主机集群，不支持从 ONTAP 中删除卷。 


| vVol | 是，有条件地 | 一个或多个 vVols 存在于数据存储库中。 | 您可以选择从 ONTAP 中删除卷，但在 ASA r2 上不支持通过此工作流从 ONTAP 中删除后备卷。 
|===
.步骤
. 登录到 vSphere 客户端。
. 右键单击主机系统、主机集群或数据中心，然后选择*NetApp ONTAP tools* > *Delete datastore*。
+

NOTE: 无法删除虚拟机使用的数据存储库。请在删除之前将虚拟机移动到另一个数据存储库。

+

NOTE: 如果数据存储区是受保护主机群集的一部分，请在删除之前查看保护约束。

+
.. 对于 NFS 或 VMFS 数据存储库，将显示一个对话框，其中包含使用该数据存储库的虚拟机列表。
.. 如果没有虚拟机与 VMFS 数据存储关联，则会看到确认对话框。如果启用了主机集群保护，并且存在自动故障转移双工 (AFD) 关系，则可以清理辅助存储元素。
.. 对于 ASA r2 存储系统上的受保护 VMFS 数据存储区，请在删除之前先移除保护。从 ONTAP 9.17.1 和 ONTAP tools for VMware vSphere 10.5 开始，您可以删除受保护的数据存储区。
+
对于使用自动故障转移双工（AFD）的最后一个数据存储删除，ONTAP tools 会显示以下消息：*数据存储受到保护。保护将在删除之前移除。*

+
如果删除保护组中的最后一个受保护数据存储库，ONTAP tools 会显示一条消息，指出删除最后一个数据存储库会导致数据存储库不受保护。

.. 对于vVols数据存储，仅当不存在vVols时才可以删除数据存储。  *删除数据存储*对话框包含从ONTAP集群中删除卷的选项。
.. 对于 ASA r2 存储系统上的 vVols 数据存储区，您无法使用*删除数据存储区*选项从 ONTAP 中删除后备卷。


. 要删除ONTAP存储上的后备卷、请选择*删除ONTAP集群上的卷*。
+

NOTE: 对于属于受保护主机集群的 ONTAP 存储上的 VMFS 数据存储区，无法从 ONTAP 集群中删除卷。



删除 NFS、VMFS 或 vVols 数据存储区时，父 igroup 仍保留在 ONTAP 系统上。未映射到任何 LUN 的子 igroup 将自动删除。ONTAP tools 每天执行清理操作，以删除未映射的默认父 igroup。请在 ONTAP 中手动删除自定义父 igroup。ONTAP tools 无法重用过时的父 igroup。
