---
permalink: manage/delete-ds.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: 删除数据存储库操作将删除此数据存储库。如果使用的是NFS或VMFS数据存储库、则会显示一个对话框、其中列出了正在使用该数据存储库的虚拟机。 
---
= 删除数据存储库
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本页介绍如何使用 vCenter Server 中的ONTAP工具删除 NFS、VMFS 或vVols数据存储。

删除数据存储区时，将根据数据存储区类型执行以下操作：

* vVol 容器已卸载。
* 如果 igroup 未被使用，则 iqn 将从 igroup 中删除。
* vVol 容器已被删除。
* 弹性卷留在存储阵列上。


仅当所选数据存储上不存在vVols时，您才可以删除该数据存储。

.步骤
. 登录到vSphere Client。
. 右键单击主机系统、主机集群或数据中心，然后选择 * NetApp ONTAP工具* > * 删除数据存储*。
+

NOTE: 您不能删除虚拟机使用的数据存储区。删除之前，将虚拟机移动到另一个数据存储。如果卷是受保护主机群集的一部分，则您无法删除该卷。

+
.. 对于 NFS 或 VMFS 数据存储，将出现一个对话框，其中列出使用该数据存储的虚拟机列表。
.. 如果没有虚拟机与 VMFS 数据存储关联，您将看到一个确认对话框。如果启用了主机集群保护并且存在 AFD 关系，则可以清理辅助存储元素。
.. 对于ASA r2 系统上的受保护 VMFS 数据存储，请在删除之前移除保护。从ONTAP 9.17.1 和ONTAP tools for VMware vSphere开始，您可以删除受保护的数据存储库。如果它是保护组中唯一的数据存储，则主机集群保护会自动移除。
.. 对于vVols数据存储，仅当不存在vVols时才可以删除数据存储。  *删除数据存储*对话框包含从ONTAP集群中删除卷的选项。
.. 对于ASA r2 系统上的vVols数据存储，您无法使用 *删除数据存储* 选项从ONTAP中删除后备卷。


. 要删除ONTAP存储上的后备卷、请选择*删除ONTAP集群上的卷*。
+

NOTE: 对于统一ONTAP存储上属于受保护主机集群的 VMFS 数据存储库，您无法从ONTAP集群中删除该卷。



当您删除 NFS、VMFS 或vVols数据存储库时，父 igroup 仍保留在ONTAP系统上。未映射到任何 LUN 的子 igroup 将被自动删除。ONTAP工具每天执行清理以删除未映射的默认父 igroup。在ONTAP中手动删除自定义父级 igroup。  ONTAP工具无法重用过时的父 igroup。
