---
permalink: manage/edit-appliance-settings.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用ONTAP工具管理器更改管理员密码。 
---
= 更改适用于VMware vSphere的ONTAP工具配置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用ONTAP工具管理器来扩展ONTAP tools for VMware vSphere，方法是增加节点数量或启用高可用性 (HA)。默认情况下，ONTAP tools for VMware vSphere部署为单节点、非 HA 配置。

.开始之前
* 确保您的OVA模板与节点1的OVA版本相同。节点1是最初部署适用于VMware vSphere的ONTAP工具OVA的默认节点。
* 确保已启用CPU热添加和内存热插拔。
* 在 vCenter Server 中，将灾难恢复服务 (DRS) 自动化级别设置为部分自动化。部署 HA 后，将其恢复为完全自动化。
* HA 设置中的节点主机名应采用小写。


.步骤
. 从Web浏览器启动ONTAP工具管理器： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期间提供的适用于VMware vSphere的ONTAP工具管理员凭据登录。
. 在概述部分中选择*编辑设备设置*。
. 在“配置”部分，扩大节点规模并启用 HA 配置。使用 vCenter Server 凭据进行更改。
+
在 HA 配置中，您可以更改内容库详细信息。每次编辑都需要提供密码。

+

NOTE: 在ONTAP tools for VMware vSphere中，您只允许增加节点大小；而不能减少节点大小。在非 HA 设置中，仅支持中等规模的配置。在 HA 设置中，支持中型和大型配置。

. 使用HA切换按钮启用HA配置。在*HA设置*页面上，确保：
+
** 内容库属于运行ONTAP工具节点VM的同一vCenter Server。vCenter Server凭据用于验证和下载OVA模板以了解设备更改。
** 托管ONTAP工具的虚拟机不会直接部署在ESXi主机上。虚拟机应部署在集群或资源池上。
+

NOTE: 启用 HA 配置后，您无法恢复到非 HA 单节点配置。



. 在*编辑设备设置*窗口的*HA设置*部分中，可以输入节点2和3的详细信息。适用于VMware vSphere的ONTAP工具支持在HA设置中使用三个节点。
+

NOTE: ONTAP工具会预先填充大多数输入选项中的 Node 1 网络详细信息，以简化工作流程。在进入向导的最后一页之前，您可以编辑输入数据。仅当在ONTAP工具管理节点上启用 IPv6 地址时，您才可以输入其他两个节点的 IPv6 地址详细信息。

+
确保ESXi主机仅包含一个ONTAP Tools VM。每次进入下一窗口时、系统都会验证输入。

. 查看*摘要*部分中的详细信息并*保存*更改。


.下一步是什么？
*概览*页面显示部署的状态。您还可以通过作业 ID 从作业视图跟踪编辑设备设置作业状态。

如果 HA 部署失败且新节点状态为“新建”，请在 vCenter 中删除新虚拟机，然后再尝试启用 HA。

左侧面板上的*警报*选项卡列出了适用于VMware vSphere的ONTAP工具的警报。
