---
permalink: manage/edit-appliance-settings.html 
sidebar: sidebar 
keywords: scale ONTAP tools appliance, enable high availability, ONTAP tools HA configuration, appliance scaling settings 
summary: '使用 ONTAP tools Manager 扩展 ONTAP tools 设备并配置高可用性 (HA)。' 
---
= 扩展 ONTAP tools 并启用高可用性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 ONTAP tools Manager 扩展您的设备并配置高可用性 (HA)。默认情况下，ONTAP tools for VMware vSphere 部署为单节点、非 HA 配置。

.开始之前
* 请确保您的 OVA 模板与节点 1（初始部署节点）的版本相匹配。
* 在虚拟机监控程序上启用 CPU 热添加和内存热插拔。扩展设备并启用 HA 需要这些功能。对于 ONTAP tools 10.6 及更高版本，默认情况下已启用这些功能。对于早期版本，请在扩展或启用 HA 之前启用这些功能。
* 在 vCenter Server 中，将灾难恢复服务 (DRS) 自动化级别设置为部分自动化。HA 部署完成后，恢复为完全自动化。
+

NOTE: 您只能增加节点大小，而不能减少它。超小型 (XS) 部署会限制某些服务。



.步骤
. 启动 ONTAP tools Manager： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您的 ONTAP tools 管理员凭据登录。
. 从概述部分选择*编辑设备设置*。
. 在 *Configuration* 部分，选择您的新节点大小并切换 HA 开关以启用高可用性。
. 在 *HA 设置*页面上，验证以下内容：
+
** 内容库位于 ONTAP tools 虚拟机将运行的同一 vCenter 服务器上。
** ONTAP tools 虚拟机部署在集群或资源池中，而不是直接部署在 ESXi 主机上。
+

IMPORTANT: 启用 HA 后，无法恢复到非 HA 单节点配置。



. 在 *HA settings* 部分，输入节点 2 和 3 的网络详细信息。ONTAP tools 在 HA 模式下支持三个节点。
+
ONTAP tools 使用节点 1 网络设置预填充大多数字段。您可以在完成向导之前编辑这些值。仅当在管理节点上启用 IPv6 时，IPv6 地址条目才可用。确保每个 ESXi 主机仅托管一个 ONTAP tools 虚拟机。

. 查看摘要，然后单击 *Save*。


.结果
设备开始扩展和启用 HA。在*概述*页面上监控进度，或使用作业 ID 从*作业*视图跟踪作业。

如果 HA 部署失败，状态为"New"，请在 vCenter 中删除失败的 VM，然后重试。

查看*警报*选项卡，了解流程中的任何警告或问题。
