---
permalink: manage/edit-hostcluster-protection.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: 您可以编辑受保护主机集群的SnapMirror关系。您可以添加、修改和删除这些关系。但是、您不能编辑一致性组名称。 
---
= 修改受保护的主机集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在单个工作流程中更改主机群集的保护设置。支持以下更改：

* 向受保护集群添加新的数据存储库或主机。
* 将新的SnapMirror关系添加到保护设置。
* 从保护设置中删除现有SnapMirror关系。
* 修改现有SnapMirror关系。



NOTE: 在创建、编辑或删除主机群集的保护后，您需要执行存储发现以反映更改。如果您不执行存储发现，则更改将在触发定期存储发现后反映出来。



== 监控主机集群保护

监控每个受保护主机集群的保护状态、 SnapMirror关系、数据存储库和SnapMirror状态。

.步骤
. 登录到vSphere Client。
. 转到 * NetApp ONTAP工具* > *保护* > *主机集群关系*。
+
保护栏显示一个图标，表示保护状态。

. 将鼠标悬停在图标上可查看更多详细信息。




== 添加新数据存储库或主机

使用 vCenter 用户界面在受保护的集群上添加主机或创建数据存储区。

.步骤
. 登录到vSphere Client。
. 要编辑受保护集群的属性、您可以执行以下任一操作
+
.. 转到 * NetApp ONTAP工具 * > * 保护 * > * 主机集群关系 *，选择集群旁边的省略号菜单，然后选择 * 编辑 * 或
.. 右键单击主机集群并选择 * NetApp ONTAP工具* > *保护集群*。


. 如果您在 vCenter 用户界面中创建数据存储区，它将显示为不受保护。您可以在对话框中查看集群中的所有数据存储及其保护状态。选择“*保护*”按钮以启用保护。
+

NOTE: 在 vCenter Server 用户界面中创建数据存储后，在概览页面上选择“发现”以将该数据存储显示为主机群集中需要保护的候选对象。下一次定期保护发现后，保护状态将更新为受保护。

. 如果添加新的 ESXi 主机，保护状态将显示为部分受保护。选择SnapMirror设置下的省略号菜单，然后选择 *编辑* 来设置新添加的 ESXi 主机的接近度。
+

NOTE: 对于异步关系， ONTAP工具不支持编辑，因为无法将第三站点的目标 SVM 添加到同一实例。要修改关系配置，请使用 System Manager 或目标 SVM 上的 CLI。

. 进行更改后，选择*保存*。
. 您可以在*Protect Cluster*窗口中看到所做的更改。


ONTAP工具创建一个 vCenter 任务，您可以在 *最近任务* 面板中跟踪其进度。



== 添加新的SnapMirror关系

.步骤
. 登录到vSphere Client。
. 要编辑受保护集群的属性、您可以执行以下任一操作
+
.. 转到 * NetApp ONTAP工具 * > * 保护 * > * 主机集群关系 *，选择集群对应的省略号菜单，然后选择 * 编辑 * 或
.. 右键单击主机集群并选择 * NetApp ONTAP工具* > *保护集群*。


. 选择*添加关系*。
. 将新关系添加为*异 步*或*AutomatedFailOverDw双 工*策略类型。
. 选择*保护*。
+
您可以在*Protect Cluster*窗口中看到所做的更改。



ONTAP工具创建一个 vCenter 任务，您可以在 *最近任务* 面板中跟踪其进度。



== 删除现有SnapMirror关系

要删除SnapMirror异步关系，请确保将辅助站点 SVM 或集群添加为适用ONTAP tools for VMware vSphere中的存储后端。您不能一次删除所有SnapMirror关系。删除关系也会从ONTAP集群中删除相应的关系。当您删除自动故障转移双工SnapMirror关系时，系统将取消目标数据存储的映射，并从目标ONTAP集群中删除一致性组、LUN、卷和 igroup。

当您删除关系时，系统会重新扫描辅助站点以从主机中删除未映射的 LUN 作为活动路径。

.步骤
. 登录到vSphere Client。
. 要编辑受保护集群的属性、您可以执行以下任一操作
+
.. 转到 * NetApp ONTAP工具 * > * 保护 * > * 主机集群关系 *，选择集群对应的省略号菜单，然后选择 * 编辑 * 或
.. 右键单击主机集群并选择 * NetApp ONTAP工具* > *保护集群*。


. 选择SnapMirror设置下的省略号菜单，然后选择*Delete*。
+
** 如果删除受保护主机群集的基于异步策略类型的关系，则必须手动从第三存储群集中删除存储元素。存储元素包括一致性组、卷（用于ONTAP系统）、存储单元（LUN/命名空间）和快照。
** 如果删除受保护主机群集的基于自动故障转移双工 (AFD) 策略的关系，则可以选择直接从界面删除辅助存储上的相关存储元素。
** 如果您删除基于自动故障转移双工 (AFD) 策略的关系，并且一致性组现在是针对应用程序级备份的分层结构，则会出现有关备份影响的警告。确认继续。确认后，删除辅助存储上关联的存储元素。如果您不删除它们，它们将保留在辅助站点上。




ONTAP工具创建一个 vCenter 任务，您可以在 *最近任务* 面板中跟踪其进度。



== 修改现有SnapMirror关系

要修改SnapMirror异步关系，请确保将辅助站点 SVM 或集群添加为适用ONTAP tools for VMware vSphere中的存储后端。对于自动故障转移双工SnapMirror关系，您可以更新主机邻近度以实现统一配置，或更新主机访问以实现非统一配置。不支持在异步和自动故障转移双工策略类型之间进行更改。您可以为集群中新发现的主机配置邻近度或访问设置。


NOTE: 您无法编辑现有的SnapMirror异步关系。

.步骤
. 登录到vSphere Client。
. 要编辑受保护集群的属性、您可以执行以下任一操作
+
.. 转到 * NetApp ONTAP工具 * > * 保护 * > * 主机集群关系 *，选择集群对应的省略号菜单，然后选择 * 编辑 * 或
.. 右键单击主机集群并选择 * NetApp ONTAP工具* > *保护集群*。


. 如果选择了 AutomatedFailOverDuplex 策略类型，请添加主机邻近度或主机访问详细信息。
. 选择“*保护*”按钮。


ONTAP工具创建 vCenter 任务。在*最近任务*面板中跟踪其进度。
