---
permalink: manage/edit-appliance-settings.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用ONTAP工具管理器更改管理员密码。 
---
= 编辑设备设置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用ONTAP工具管理器纵向扩展节点大小、管理服务以及将适用于VMware vSphere的ONTAP工具升级到高可用性(HA)设置。

ONTAP工具设备最初部署在单节点非HA配置中。您可以在*编辑设备设置*窗口中编辑配置。

* 开始之前 *

确保您提供的OVA模板与第一个节点具有相同的OVA版本。

* 步骤 *

. 从Web浏览器启动ONTAP工具管理器： `\https://loadBalancerIP:8443/virtualization/ui/`
. 使用您在部署期间提供的适用于VMware vSphere的ONTAP工具管理员凭据登录。
. 在概述部分中选择*编辑设备设置*。
. 在*服务*部分中，您可以根据需要启用VASA Provider、导入VVOLs配置和灾难恢复(SRA)等可选服务。
+
首次启用服务时、您需要创建VASA Provider/SRA凭据。用于在vCenter Server上注册或启用VASA Provider/SRA服务。

+

NOTE: 要禁用任何可选服务、请确保由ONTAP工具管理的vCenter Server均未使用这些服务。

+
*仅当启用了VASA Provider服务时、才会显示允许导入vvol配置*选项。通过此选项、可以将ONTAP工具9.x中的数据迁移到ONTAP工具10.3。

. 在*Configuration*部分中，您可以根据需要纵向扩展每个ONTAP工具节点大小并启用HA配置。要进行任何更改、您需要vCenter Server凭据。
+
如果ONTAP工具采用HA配置、则可以更改内容库详细信息。您应该为新的编辑提交重新提供密码。

+

NOTE: 您只能纵向扩展ONTAP工具节点大小。您不能将节点从当前大小缩减为较小的大小。非HA支持的最大配置为中等。对于HA、支持中型和大型配置。

. 使用HA切换按钮启用HA配置。如果选择HA配置，则会显示一个附加的*HA设置*页面，用于输入与HA相关的内容。
+
** 内容库应属于运行ONTAP工具节点VM的同一vCenter Server。vCenter Server凭据用于验证和下载OVA模板以了解设备更改。
** 要启用HA部署、不应将托管ONTAP工具的虚拟机直接部署在ESXi主机上。而是应将其部署在集群或资源池上。
** 启用后、您将无法从HA配置还原到非HA单节点配置。


. 在*编辑设备设置*窗口的*HA设置*部分中，可以输入节点2和节点3的详细信息。节点1是部署在OVA中的ONTAP工具默认节点。适用于VMware vSphere的ONTAP工具支持在HA设置中使用三个节点。
+

NOTE: 为了简化工作流、大多数输入选项都预先填充了节点1网络详细信息。但是、您可以在导航到向导的最后一页之前编辑输入数据。只有在第一个节点上启用了IPv6地址后、才能输入其他两个节点的IPv6详细信息。

+
确保ESXi主机仅包含一个ONTAP Tools VM。每次进入下一窗口时、系统都会验证输入。

. 在*摘要*部分中，查看详细信息并选择*Save*以应用更改。


“*Overview*”页面显示部署的状态。使用作业ID、您还可以从作业视图跟踪编辑设备设置作业状态。

如果HA部署失败、并且新节点的状态显示为‘New’(新建)、则在重试启用HA操作之前、请删除vCenter中的新VM。

左侧面板上的*警报*选项卡列出了适用于VMware vSphere的ONTAP工具的警报。
