---
permalink: manage/manage-vcenter.html 
sidebar: sidebar 
keywords: manage vCenter instances, add remove vCenter, ONTAP tools vCenter credentials, vCenter certificate management 
summary: 在 ONTAP tools 中管理 vCenter 实例，以控制主机、虚拟机和存储后端。 
---
= 在ONTAP工具中管理 vCenter Server 实例
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
vCenter Server 实例是集中管理平台，可让您控制主机、虚拟机和存储后端。在 ONTAP tools 中，您可以分离存储后端、修改实例详细信息、删除实例和续订 vCenter Server 证书。



[[dissociate-storage-backends-from-a-vcenter-server-instance]]
== 将存储后端与 vCenter Server 实例解除关联

vCenter Server列表页面会显示相关的存储后端数量。每个vCenter Server实例都可以选择与存储后端关联或解除关联。

.步骤
. 从Web浏览器启动ONTAP工具管理器： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期间提供的适用于VMware vSphere的ONTAP工具管理员凭据登录。
. 从侧栏中选择 *vCenters*。
. 选择要与存储后端关联或解除关联的 vCenter Server 的垂直省略号（⋮）。
. 选择*取消关联存储后端*。




[[modify-a-vcenter-server-instance]]
== 修改vCenter Server实例

通过完成以下步骤修改 vCenter Server 实例。

. 从Web浏览器启动ONTAP工具管理器： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期间提供的适用于VMware vSphere的ONTAP工具管理员凭据登录。
. 从侧栏中选择 *vCenters*。
. 选择要修改的 vCenter Server 的垂直省略号，然后选择*修改*。
. 在“修改 vCenter”窗口中，输入用户名、密码和端口详细信息。
. 上传证书并选择*Modify*。




[[remove-a-vcenter-server-instance]]
== 删除vCenter Server实例

即使数据存储区和存储后端仍然关联，也可以删除 vCenter 服务器实例。*删除 vCenter* 对话框将根据 vCenter 服务器的当前状态引导您完成所有必需的操作。


NOTE: 强制删除仅删除 ONTAP tools 元数据。它不会删除 ONTAP 存储对象（卷或 LUN）、vSphere 数据存储区或虚拟机。

.开始之前
如果 vCenter Server 具有 vVols 数据存储或受保护的数据存储，则强制删除将被阻止。在继续之前：

* 删除或迁移所有 vVols 数据存储库。
* 取消对所有受保护数据存储库的保护。
* 确保没有正在运行的发现作业。如果正在执行发现作业，强制删除操作将不会继续。



NOTE: 与其他 vCenter Server 实例共享的全局存储后端将被保留。仅删除与已删除的 vCenter Server 的关联。

.步骤
. 从Web浏览器启动ONTAP工具管理器： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期间提供的适用于VMware vSphere的ONTAP工具管理员凭据登录。
. 从侧栏中选择 *vCenters*。
. 选择所需 vCenter Server 的垂直省略号，然后选择 *Remove*。
. 在*删除 vCenter* 对话框中，查看 vCenter Server 的状态并完成所有必需的操作。
+
对话框行为取决于 vCenter 服务器的状态：

+
[cols="2,2,3"]
|===
| 条件 | 对话行为 | 需要执行的操作 


| 没有 vVols 或受保护的数据存储，但存储后端已关联 | 该对话框显示关联的存储后端和数据存储区的数量。 | 选择*从此 vCenter Server 中删除所有存储工件*和*我了解关联的数据存储将不再由 ONTAP tools 管理*。 


| 无 vVols 数据存储区、受保护数据存储区或存储后端 | 对话框确认删除。 | 无需执行其他操作。 
|===
. 选择*强制删除*。
. 确认此操作。


.结果
ONTAP tools 会自动执行以下操作：

* 已取消注册插件。
* 插件权限和插件角色将被删除。


vCenter 服务器实例不再由 ONTAP tools 管理。

如果在删除过程中无法访问 vCenter 服务器：

* ONTAP tools 删除 vCenter Server 记录。
* 未进行插件注销。
* 此时将显示警告。
* 您必须从 VMware vCenter Server 手动注销该插件。




[[renew-vcenter-server-certificate]]
== 更新 vCenter Server 证书

ONTAP工具会在 vCenter 证书即将到期或已过期时通知您。更新 vCenter 证书后，请按照以下步骤将新证书上传到ONTAP工具：

. 登录到ONTAP工具远程诊断 shell。
. 从诊断 shell 获取更新后的 vCenter 证书：
+
[listing]
----
echo | openssl s_client connect <vcenter>:443 2>&1 | sed -n '/-BEGIN CERTIFICATE/,/END CERTIFICATE/p'
----
. 验证证书是否为 Base 64 ASCII 格式，并包括开始行和结束行，例如：
+
[listing]
----
---{}BEGIN CERTIFICATE{}---
MIIFUzCCA7ugAwIBAgIJANOgLapcl5oSMA0GCSqGSIb3DQEBCwUAMIGJMQwwCgYD
VQQDDAN2YzExFDASBgoJkiaJk/IsZAEZFgRkZW1vMRUwEwYKCZImiZPyLGQBGRYF
bG9jYWwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRwwGgYDVQQK
DBN2YzEuZGVtby5uZXRhcHAuY29tMQwwCgYDVQQLDANMT0QwHhcNMjQwNDA1MTgw
NTE4WhcNMjYwNDA1MTgwNTE4WjBzMRwwGgYDVQQDDBN2YzEuZGVtby5uZXRhcHAu
Y29tMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJ
UGFsbyBBbHRvMQ8wDQYDVQQKDAZOZXRBcHAxDDAKBgNVBAsMA0xPRDCCAaIwDQYJ
KoZIhvcNAQEBBQADggGPADCCAYoCggGBALU8OCWMtA2gvIC/OTw/7xucvPVuM+b8
DhzvNpQ2phjfr6ctEhbntPpqPdu+t2CKK7l0mzg3D9cJ/rvMvdDDXr0tgaD1oi2u
ZDW0CaF0QhLOpNfRXMoogBZ66csEhViAy3CHTcOse770mA/PyoHgrCPZngVlZIiQ
TIWpdQMbEEzFIkrLfC70UW2MzfublrsH7Dn/kOu/iCSlVJWixKf7SmZtVQ5ZxBTD
UlJSiqoX1eRXGyunArEvrIpOY9kkKXUElm3hGnk/ZmiuBJ+HqUYqYW+H+7vE3lKa
6NEqDX+tZotxTx2bXMjeiIWU30ZbshgeXlIG9qc49clBoC9iGjavhctOcaXg/W3h
dLKK5ds3rpRERgMg6VMkrfiqAJuiq+b3sTvXMAul/3hL7hz5QABAE/hP4ZvIHV02
WWDQRLiuVFAcDAyvCrO9Irx0Gk1RyRShKYakdWxZ3hhMdLuGq0yvRXqo1Ib94zwO
JfBJHjFToA/GqwromZgiTzJkKq5xbN8MFwIDAQABo4HSMIHPMAsGA1UdDwQEAwIF
4DA7BgNVHREENDAygRVlbWFpbEBkZW1vLm5ldGFwcC5jb22HBMCoAB+CE3ZjMS5k
ZW1vLm5ldGFwcC5jb20wHQYDVR0OBBYEFJ0V0zY+JRpFrEt31ovAY4BLFXmAMB8G
A1UdIwQYMBaAFENf6fRxWF3OJQNTPIdUpK6kjA78MEMGCCsGAQUFBwEBBDcwNTAz
BggrBgEFBQcwAoYnaHR0cHM6Ly92YzEuZGVtby5uZXRhcHAuY29tL2FmZC92ZWNz
L2NhMA0GCSqGSIb3DQEBCwUAA4IBgQBaDfk7GBM4vmhzYCqGrr6KB+h3qeTJ+Y0Y
5nIPRP1HucawDQ8QTay605ddJ8gFGoxkOQDn9tdXWXGjnTRFOT8R+Hw/nUfVSiDP
sYienb16copzUNwtqh+m9Ifow74Gf+ulRzEC0EAVO1X/nTEYH6NKM6Wy7y7F8g5J
lrpM3JY90ZChMqHO3Av/88rbErfQ/gU1brJ3u9Gks4e20Z7Ff312ZKhWRuJDlN2Z
0tc/gp90N9GxaVvELovq/pdjaZ8xiXCxa6piicrJd9WnqMH1gmxP2PIBDxMDBWBG
gwsfs5H7VG9MJYks6lViNsGclo0EwEdF0MfoB3JtsWpPWq6+jBua0Jm7/aFCU+Ht
mykr0gaV7muegoiBQuDma4EkAI31D7ZlUgJQaw157NTk4RW3TFcbtViBHJkM54Hr
iVm0cl+2BZNi/QTMh/MkWV2dYXJ3NuNlqqfzFY+bUfkzkR4SneMk0HX3joNNYDJv
siO7bL+k/Pxql27NVIhuCoVJAlcI7ak=
---{}END CERTIFICATE{}---
----
. 复制输出结果并将其另存为文本文件。 `.pem` 桌面扩展程序。
. 从Web浏览器启动ONTAP工具管理器： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期间提供的适用于VMware vSphere的ONTAP工具管理员凭据登录。
. 从侧栏中选择适用的vCenter Server实例
. 选择要修改的 vCenter Server 的垂直省略号，然后选择*修改*。
. 在“修改 vCenter”窗口中，输入用户名、密码和端口详细信息。
. 上传证书并选择*Modify*。


.相关信息
link:../manage/configure-remote-diagnostic-access.html["配置远程诊断访问"]
