---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: 在数据中心中迁移现有虚拟机时、您应了解一些注意事项。 
---
= 迁移或克隆虚拟机的注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
迁移数据中心中的现有虚拟机时、您应了解一些注意事项。



== 迁移受保护的虚拟机

您可以将受保护虚拟机迁移到：

* 同一个 VVol 数据存储库位于不同的 ESXi 主机中
* 同一 ESXi 主机中的不同兼容 VVol 数据存储库
* 不同 ESXi 主机中的不同兼容 VVol 数据存储库


如果将虚拟机迁移到不同的FlexVol volume，系统会使用虚拟机信息更新该卷的元数据文件。如果虚拟机迁移到不同的 ESXi 主机但相同的存储，则底层FlexVol volume数据文件将不会被修改。



== 克隆受保护的虚拟机

您可以将受保护虚拟机克隆到以下位置：

* 同一个 FlexVol 卷的同一个容器使用复制组
+
同一个 FlexVol 卷的元数据文件将使用克隆的虚拟机详细信息进行更新。

* 使用复制组的不同 FlexVol 卷的同一容器
+
放置克隆虚拟机的 FlexVol 卷，元数据文件将使用克隆的虚拟机详细信息进行更新。

* 不同的容器或 VVOL 数据存储库
+
放置克隆虚拟机的 FlexVol 卷，元数据文件将获取更新后的虚拟机详细信息。



VMware 目前不支持将虚拟机克隆到 VM 模板。

支持受保护虚拟机的克隆。

有关详细信息、请参见 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["创建虚拟机以进行克隆"]。



== 虚拟机快照

目前仅支持不含内存的虚拟机 Snapshot 。如果虚拟机具有带有内存的 Snapshot ，则不会考虑对该虚拟机进行保护。

您也无法保护具有内存快照的未受保护的虚拟机。对于此版本，您需要在启用虚拟机保护之前删除内存快照。

对于采用ASA r2 存储类型的 Windows VM，虚拟机的快照是只读的。当您启动虚拟机时，VASA Provider 会从只读快照创建 LUN 并启用 IOPS。关闭虚拟机电源时，VASA Provider 会删除 LUN 并禁用 IOPS。
