---
permalink: manage/recover-backup.html 
sidebar: sidebar 
keywords: recover ONTAP tools setup, appliance recovery workflow, near zero RPO recovery, restore ONTAP tools configuration 
summary: 从备份中恢复 ONTAP tools，并按版本了解零 RPO 和接近零 RPO 的行为。 
---
= 从备份中恢复 ONTAP tools for VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过恢复存储在数据存储区上的备份文件，恢复 ONTAP tools for VMware vSphere。从 ONTAP tools for VMware vSphere 10.5 开始，默认情况下会启用备份，因此如果您需要重新部署或恢复设备，通常可以使用最近的备份。

用于部署 ONTAP tools for VMware vSphere 虚拟机的数据存储区存储备份文件。以 ONTAP tools IP 地址命名的文件夹存储两个最新备份文件（_OTV_backup_1.tar.enc_ 和 _OTV_backup_2.tar.enc_）以及标识最新备份的信息文件（_OTV_backup_info.txt_）。

确保新虚拟机使用相同的ONTAP工具 IP 地址并与初始系统配置相匹配，包括启用的服务、节点大小和 HA 模式。

.步骤
. 将备份文件从原始虚拟机的数据存储下载到本地系统。
+
.. 转到存储部分并选择包含虚拟机备份文件的数据存储。
.. 选择*Files*部分。
.. 下载所需的备份目录。


. 关闭现有虚拟机。然后，使用与原始部署相同的 OVA 文件部署新的虚拟机。
. 登录到 vCenter 服务器。
. 找到新部署的 ONTAP tools VM 并启动 Web 控制台。
. 使用 `maint`凭据登录。
. 输入 `4`以选择*Support and Diagnostic*。
. 输入 `2`以选择*Enable remote diagnostic access*选项并为诊断访问创建新密码。
. 从下载的目录中选择一个备份文件。请参阅_OTV_backup_info.txt_文件来识别最新的备份。
. 使用以下命令将备份文件传输到新的虚拟机。出现提示时，输入诊断密码。
+
[listing]
----
scp <OTV_backup_X.tar.enc> diag@<node_ip>:/home/diag/system_recovery.tar.enc
----
+

NOTE: 请勿更改命令中提到的目标路径和文件名(/home/diag/system_recovery.tar.enc)。

. 备份文件传输完成后，登录诊断shell并运行以下命令：
+
[listing]
----
sudo perl /home/maint/scripts/post-deploy-upgrade.pl -recovery
----
+
日志记录在 _/var/log/otvng/post-deploy-upgrade.log_ 文件中。



完成恢复后， ONTAP工具将恢复服务和 vCenter 对象。
